### ISSUE TITLE
chromeで「中国語を翻訳しますか」と表示される

### ISSUE THREAD

**Issue by naclyhara** [shugo/roomresrv#18]
google chromeで開いたときに、ページが中国語だと判定されるようです。

`<html lang="en">`が原因かもしれません。

**Comment by shugo** [comment]
@naclyhara UbuntuのChromeでは再現しませんでしたが、lang="ja"にしてみましたので確認をお願いします

**Comment by naclyhara** [comment]
直りました 😄
