### ISSUE TITLE
ブラウザの戻るボタンでカレンダーが二重に表示される

### ISSUE THREAD

**Issue by shugo** [shugo/roomresrv#6]
以下の手順でカレンダーが二重に表示されるバグを修正する。

1. カレンダー上の予定をクリックして予定の詳細を表示する
2. ブラウザの戻るボタンでカレンダーに戻る

**Comment by 723gt** [comment]
app/view/calendar/index.html.erbに
`<script>
    $(document).on('turbolinks:before-render',function(){
      console.log("hoge")
      location.reload()
    });
  </script>
`
を追加しました。
バグは改善されましたが、レンダリングし直すので時間がかかります
